##NUTRITION
maternal_height = {'id':1, 'key': 'mother_height','desc': "Proportion of pregnant women with height <150cm at 1st ANC"}
maternal_bmi = {'id':2, 'key1': 'bmi', 'key2': 'mother_weight', 'desc': "Proportion of pregnant women with BMI <18.5 at 1st ANC"}
maternal_anc = {'id':3, 'key': 'anc3','desc': "Proportion of pregnant women attending 3rd ANC (drop-out rate)"}
birth_weight = {'id':4, 'key': 'child_weight','desc': "Proportion of live births with birth weight below 2.5kg"}
birth_term = {'id':5, 'key': 'te','desc': "Proportion of live births born at term"}
vaccination_dpt3 = {'id':6, 'key': 'v3','desc':"Proportion of children receiving DPT3 (6 months old)"}
vaccination_measles = {'id':7, 'key': 'v5','desc':"Proportion of children receiving measles (9 months old) vaccinations"}
ebf1 = {'id':8, 'key': 'ebf1','desc':"Proportion of live births breastfed within 1st hour"}
ebf2 = {'id':9, 'key': 'ebf2','desc':"Proportion of live births breastfed within 2 days"}
ebf3 = {'id':10, 'key': 'ebf3','desc':"Proportion of live births breastfed within 6 days"}
ebf4 = {'id':11, 'key': 'ebf4','desc':"Proportion of live births breastfed within 28 days"}
pnc1 = {'id':12, 'key': 'pnc1','desc':'Proportion of mother-baby pairs that receive PNC visit within 2 days'}
pnc2 = {'id':13, 'key': 'pnc2','desc':'Proportion of mother-baby pairs that receive PNC visit within 6 days'}
pnc3 = {'id':14, 'key': 'pnc3','desc':'Proportion of mother-baby pairs that receive PNC visit within 28 days'}
anthro_h_6 = {'id':15, 'key':'child_height' , 'desc': 'Proportion of children whose height is measured at 6 months old.'}
anthro_h_9 = {'id':16, 'key':'child_height' , 'desc': 'Proportion of children whose height is measured at 9 months old.'}
anthro_h_18 = {'id':17, 'key':'child_height' , 'desc': 'Proportion of children whose height is measured at 18 months old.'}
anthro_h_24 = {'id':18, 'key':'child_height' , 'desc': 'Proportion of children whose height is measured at 24 months old.'}
anthro_w_6 = {'id':19, 'key': 'child_weight', 'desc': 'Proportion of children whose weight is measured at 6 months old.'}
anthro_w_9 = {'id':20, 'key': 'child_weight', 'desc': 'Proportion of children whose weight is measured at 9 months old.'}
anthro_w_18 = {'id':21, 'key': 'child_weight', 'desc': 'Proportion of children whose weight is measured at 18 months old.'}
anthro_w_24 = {'id':22, 'key': 'child_weight', 'desc': 'Proportion of children whose weight is measured at 24 months old.'}
stunted_6 = {'id':23, 'key': 'child_height', 'desc': 'Proportion of U2 children stunted at 6 months of age'}
stunted_9 = {'id':24, 'key': 'child_height', 'desc': 'Proportion of U2 children stunted at 9 months of age'}
stunted_18 = {'id':25, 'key': 'child_height', 'desc': 'Proportion of U2 children stunted at 18 months of age'}
stunted_24 = {'id':26, 'key': 'child_height', 'desc': 'Proportion of U2 children stunted at 24 months of age'}
wasted_6 = {'id':27, 'key': 'child_height', 'desc': 'Proportion of U2 children wasted at 6 months of age'}
wasted_9 = {'id':28, 'key': 'child_height', 'desc': 'Proportion of U2 children wasted at 9 months of age'}
wasted_18 = {'id':29, 'key': 'child_height', 'desc': 'Proportion of U2 children wasted at 18 months of age'}
wasted_24 = {'id':30, 'key': 'child_height', 'desc': 'Proportion of U2 children wasted at 24 months of age'}
unwe_6 = {'id':31, 'key': 'child_weight', 'desc': 'Proportion of U2 children underweight at 6 months of age'}
unwe_9 = {'id':32, 'key': 'child_weight', 'desc': 'Proportion of U2 children underweight at 9 months of age'}
unwe_18 = {'id':33, 'key': 'child_weight', 'desc': 'Proportion of U2 children underweight at 18 months of age'}
unwe_24 = {'id':34, 'key': 'child_weight', 'desc': 'Proportion of U2 children underweight at 24 months of age'}
##END OF NUTRITION
